### ISSUE TITLE
(feat): rewamp enjowtown

### ISSUE THREAD

**Issue by avalynndev** [avalynndev/enjoytown#17]
### Finished:
- [x] new home page
- [x] add manga
- [x] update card ui a bit
- [x] added redis to make loading faster
- [x] add a footer
- [x] manga page ui fix, mobile ui menu bar
- [x] add option to change subtitle language
- [x] improve info ui for movie/tv
- [x] add download anime
- [x] add better ui for blog page
- [x] use anilist api for fetching and aniwatch for playing in anime instead of gogoanime
- [x] carousel for tv, anime
- [x] add dropdown for TV series

### To-do:
- [ ] add download manga

Note: If people wanna request for more features, just add a comment here. If it find it valid, I will add it to my list

**Comment by avalynndev** [comment]
#16 is mentioned here

**Comment by flawsom** [comment]
option to download anime, i can help with this and ui

**Comment by avalynndev** [comment]
@flawsom kindly create a adding download anime option please

**Comment by avalynndev** [comment]
@flawsom download button is being added by @RounakDadsena

**Comment by avalynndev** [comment]
#31 mentioned here
